# Generated by Django 3.2.5 on 2021-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210804_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='time',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
